### ISSUE TITLE
Invalid option in build() call: "watch"

### ISSUE THREAD

**Issue by Ptico** [KingSora/rollup-plugin-esbuild-resolve#1]
It looks like esbuild introduced braking change https://github.com/evanw/esbuild/issues/2841 and this plugin is affected too

**Comment by KingSora** [comment]
@Ptico thanks for the report! I'll adapt it as soon as I have time :)

**Comment by KingSora** [comment]
@Ptico This should be fixed with version `1.3.0` :)

**Comment by Ptico** [comment]
@KingSora awesome! Thank you so much!
